### ISSUE TITLE
No result for `_.merge`

### ISSUE THREAD

**Issue by LukaszWiktor** [frakti/dexters-lab#1]
I entered ```_.merge({a: {b:1}}, {a: {c:2}})``` in the editor and no result is being displayed:

![image](https://cloud.githubusercontent.com/assets/2964543/22968650/8525fdce-f36b-11e6-9f94-bc4df07c1b5b.png)

**Comment by frakti** [comment]
Thanks for the report! 

You should include `return` statement to see the result. Going to add some hints so it's gonna be clear for newcomers.

**Comment by LukaszWiktor** [comment]
Right, thanks. What do you think about adding `return` behind the scenes if there is none?

**Comment by frakti** [comment]
I was thinking about this already, but at this stage it's tricky, someone might type complex code there.
But probably at some point will use [escodegen](https://github.com/estools/escodegen) or something similar.
